id: P000135
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །ཤེར་ཕྱིན་གྱི་ལུང་ལ་འཇུག་པའི་སྒོ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  layers:
  - book_title
  - author
  - tsawa
  - quotation
  - sabche
  id: KS-PK-11
web_metadata:
  title:
    en: Gateway to the Perfection of Wisdom
    bo: ཤེར་ཕྱིན་གྱི་ལུང་ལ་འཇུག་པའི་སྒོ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  collection:
    en: Pema Karpo Series–  Book 11
    bo: ཀུན་མཁྱེན་གཞུང་འགྲེལ།–  དེབ། ༡༡
  author:
    en: Kunkhyen Pema Karpo
    bo: ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-PK-11
  category:
    en: Prajnaparamita
    bo: ཤེས་ཕྱིན།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-PK-11.epub
  description:
    en: ''
    bo: ''
